ENG-45584 - create Config client
alertlogic/nepal-client-libs pull request #696
Opened 2022-12-05 19:49 UTC by dev4ndy

2022-12-05 21:09 UTC, dev4ndy commented
test it

2022-12-06 13:05 UTC, dadagama requested changes

2022-12-06 13:05 UTC, dadagama commented on packages/config/test/al-config-client-v2.spec.ts
> +describe('CARGO CLIENT V2', () => {
Config client, not Cargo. please fix description.

2022-12-06 13:05 UTC, dadagama commented on packages/config/test/al-config-client-v2.spec.ts
> +            it('Should call the batchDeleteSchedules (DELETE).', async () => {
not testing Delete but listing functionality. please update description accordingly

2022-12-06 13:43 UTC, dadagama approved these changes

2022-12-06 13:43 UTC, merged